# Generated by Django 2.1.4 on 2019-02-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descibe',
            new_name='describe',
        ),
    ]
